<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\ProductDBController.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Views\ProductDB\Components.cshtml" />
    <Content Remove="Views\ProductDB\Inventories.cshtml" />
    <Content Remove="Views\ProductDB\Notifications.cshtml" />
    <Content Remove="Views\ProductDB\Products.cshtml" />
    <Content Remove="Views\ProductDB\Roles.cshtml" />
    <Content Remove="Views\ProductDB\Suppliers.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PAW3.ServiceLocator\PAW3.ServiceLocator.csproj" />
  </ItemGroup>

</Project>
